### ISSUE TITLE
Attention and gpu memory

### ISSUE THREAD

**Issue by hanyang-93** [RenqiChen/Genomic-Selection#2]
There are two kinds of multi-head-attention in your code, i.e., nn.MultiheadAttention and flashattention. With your input sequence over 40k length, I guess out-of-memory might appear when you use nn.MultiheadAttention. How do you solve this problem? by using flashattention?

**Comment by RenqiChen** [comment]
Yes. In the early stages of the research, we used nn.MultiheadAttention. However, considering the long input sequence, we opted to use flashattention. However, the current version of PyTorch (torch>2.0) has integrated several technologies for acceleration and memory optimization. I think this is enough for you to run our code on an NVIDIA GeForce RTX 3090 GPU with 24GB of memory.

**Comment by hanyang-93** [comment]
Thanks for your clarification. In addition, in your primary research, may I ask you how long sequence is fine when you use nn.MultiheadAttention?

**Comment by RenqiChen** [comment]
You are welcome. In our experiments, the length of the sequence between 30k and 70k (after k-mer) is acceptable.

**Comment by hanyang-93** [comment]
HI, I have another question about flash-attention. It only supports float16 or float8, however, in your code, float32 was used. Is there something else ignored by me?

**Comment by RenqiChen** [comment]
Hello, I think the error might be caused by `apex`, but you can use `dtype=torch.float16` before using flash-attention to ensure the running of codes.

**Comment by hanyang-93** [comment]
I got it. Thanks.
