### ISSUE TITLE
missing ./configs/gwas_transformer_rice3k.json

### ISSUE THREAD

**Issue by qzhai** [RenqiChen/Genomic-Selection#4]
Dear,

I tried to test the released Rice3k dataset, but the configuration file of Rice3k is missing, while only the wheat file exists. Could you please help to update the Rice3k param file? btw, would the Wheat3d be released?

Best

**Comment by RenqiChen** [comment]
Hello, the transformer structure for these two datasets are the same, so you only need to change the parameter about the input length (data length). I am afraid that nowadays I cannot release the Wheat3k.

**Comment by RenqiChen** [comment]
{
    "width": 32, 
    "num_layers": 3,
    "num_heads": 4, 

    "hidden_dims": [512, 128],
    "dropout": 0.0,
    "filter_dim": 201740,
    "method": "MLM",
    "tokenizer": "kmer_nonoverlap",
    "max_len": 230000,
    "kmer": 5,
    "class_num": 1
}
Note that you only need to set up the `max_len`, which is used in positional embedding. Other parameters does not need to be changed.

**Comment by qzhai** [comment]
I appreciate your kind response. I'll try the code with the updated parameters. In dataset_rise3k_45.py, lines 54-57 contain excess indentations, and data loaded from xlsx_path also needs to be estimated mean/std, otherwise there will be a bug while parsing __getitem__ in GENE.

**Comment by RenqiChen** [comment]
Oh, you are right. The reason for the error may be during replication the code. Also thanks for your kind advice.

**Comment by qzhai** [comment]
> ```
> {
>     "width": 32, 
>     "num_layers": 3,
>     "num_heads": 4, 
> 
>     "hidden_dims": [512, 128],
>     "dropout": 0.0,
>     "filter_dim": 201740,
>     "method": "MLM",
>     "tokenizer": "kmer_nonoverlap",
>     "max_len": 230000,
>     "kmer": 5,
>     "class_num": 1
> }
> ```
> 
> Note that you only need to set up the `max_len`, which is used in positional embedding. Other parameters does not need to be changed.

Hi,

I'm a bit confused about the `filter_dim` setting for Rice3k. The original paper states that the SNP sequence lengths for Rice3k and Wheat3k are 201,740 and 404,388, respectively. So, to confirm, I should adjust `filter_dim` rather than `max_len`, correct? Also, could you please share the config file used for training on Rice3k?

I’ve trained the network five times (running `bash distributed_train_rice3k.sh`), but can't reproduce the accuracy, the accuracy for Rice3k remains at 0.

Thanks.
