### ISSUE TITLE
Question on Converting Genotype Formats in core_v0.7.vcf to Nucleotide Representations

### ISSUE THREAD

**Issue by XiangXiangHotSpot** [RenqiChen/Genomic-Selection#6]
I noticed that the original genotype file (core_v0.7.vcf) provides genotypes in the format 0/0, 1/0, 0/1, and 1/1. Could you please explain how to convert these into nucleotide representations (A, T, C, G, Y, K, W, R, S, M, N) as mentioned in the paper and in the Genotype/Seqs/ section?

**Comment by RenqiChen** [comment]
Hello, it is a biological question and I cannot help you to solve this issue because the preprocessed sequences are provided by my partners. I will also offer his email in Readme and you can ask him for more details.
